### ISSUE TITLE
Data Warehouse

### ISSUE THREAD

**Issue by vigonotion** [vigonotion/databases-final-project#6]
A data warehousing solution will be implemented by the use of temporal tables. It will cover products
and ratings, and it will allow to query what was a product’s description, price, rating, stock, and user
comments at a determined point in the past.

In order to test the proper operation of the data warehouse, at least 5 products should have a history
of changes in the aforementioned attributes from the time the data warehouse was implemented,
involving an average of 3 changes per product.

**Comment by vigonotion** [comment]
we have to do it in sql so we can recreate it

**Comment by pokealai** [comment]
Created a separate file that alters TRating and TProduct tables to be system versioned. Or should they just be system versioned in database/000_schema.sql?
